swagger: '2.0'
info:
  title: Bank Argent API Transactions
  description: API endpoints for managing transactions in the Argent Bank application.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all transactions for the current month
      description: Retrieve all transactions for the current month, grouped by account.
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get transaction details
      description: Retrieve the details of a specific transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid transaction ID
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
    put:
      tags:
        - Transactions Module
      summary: Update transaction details
      description: Update the details of a specific transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to update
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid transaction ID or invalid fields
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Transactions Module
      summary: Delete transaction details
      description: Delete the details of a specific transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to delete
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid transaction ID
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
  /transactions:
    post:
      tags:
        - Transactions Module
      summary: Add transaction details
      description: Add new transaction details (note: this is for adding information to an existing transaction, not creating a new transaction).
      parameters:
        - in: body
          name: body
          description: New transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionAdd'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details added successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid fields
        '500':
          description: Internal server error
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      accountId:
        type: string
        description: Account ID associated with the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Balance after the transaction
  TransactionUpdate:
    type: object
    properties:
      description:
        type: string
        description: Updated description of the transaction
      amount:
        type: number
        description: Updated amount of the transaction
      balance:
        type: number
        description: Updated balance after the transaction
  TransactionAdd:
    type: object
    properties:
      accountId:
        type: string
        description: Account ID associated with the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Balance after the transaction
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
